from pathlib import Path

DOCUMENT_UPLOAD_DIR = Path("uploads")

DOCUMENT_STATUS_UPLOADED = "uploaded"
DOCUMENT_STATUS_QUEUED = "queued"
DOCUMENT_STATUS_PROCESSING = "processing"
DOCUMENT_STATUS_EXTRACTING = "extracting"
DOCUMENT_STATUS_READY = "ready"
DOCUMENT_STATUS_FAILED = "failed"

TERMINAL_DOCUMENT_STATUSES = {
    DOCUMENT_STATUS_READY,
    DOCUMENT_STATUS_FAILED,
}
